---
title: "Live Session 5"
author: "Ben Goodwin"
date: "9/21/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
######################
#                    #
#     Libraries      #
#                    #
######################
library(dplyr)
library(tidyverse)
library(stringr)


```



```{r}
######################
#                    #
#    Question 1,R    #
#                    #
######################

#load in data and examine it
bballDat <- read.csv("bballplayers.csv")
#head(bballDat)


######################
#                    #
#  Live Session 2    #
#  Code to improve   #
######################


bballDat <- bballDat[-2143,]
View(bballDat1)#tail(bballDat)

#Convert Position data to table
counts <- table(bballDat$position)
View(counts)
counts <- na.omit(counts)
View(counts)
counts <- as.data.frame(counts)
View(counts)
View(bballDat)

counts <- counts[-1,]
View(counts)


p<-ggplot(counts, aes(x=Var1, y=Freq, color=Var1)) +geom_bar(stat="identity")
p+xlab("Player Position")+ylab("Frequency of player position")+theme_minimal()+ labs(title = "Player Positions and Frequencies")+ theme(legend.position = "none")+scale_x_discrete(labels=c("C" = "Center", "C-F" = "Center-Forward",
                              "F" = "Forward","F-C" = "Forward-Center","F-G" = "Forward-Guard","G" = "Guard","G-F" = "Guard-Forward"))+geom_text(aes(label=Freq), vjust=1.6, color="blue", size=3.5)
##################################################################################################################################################################

#Use regular expressions to use the height column to create a TotalInches column that has the total height in inches and is recorded as a numeric variable. 
#Use this variable to make a chart that contains histograms of heights for every position (color coded).  


#Use regex to create totalinches
newHeights <- bballDat %>% 
    separate(height, into = c("H1", "H2"), convert = TRUE) %>%
    transmute(H = H1 * 30.48 + H2 * 2.54)
histDF <- bind_cols(bballDat$position,newHeights$H)
histDF$...2 <- histDF$...2/2.54
colnames(histDF) <- c("Player Position","Height in inches")
View(histDF)
#Create chart that contains histograms of heights for every position
#Create new df with only variables of interest
# plot
p <- ggplot(data = histDF, aes(x = `Height in inches`,color=`Player Position`)) + geom_histogram(binwidth = 3)
p + facet_wrap(~`Player Position`)+theme_minimal()

```

```{r}
######################
#                    #
#    Question 2,R    #
#                    #
######################

#We previously used a dataset called FIFA Players.csv which contained information about Soccer players.  
#Use the string functions and regular expressions to assess a relationship between height and weight among soccer players.  To do this you will need to manipulate #the height and weight columns into columns that have numeric values of the height and weight.  Tell your story using 2 – 4 PPT Slides. 
###################################################################################################################################################################

#Read in data
FIFAdat <- read.csv("players.csv")

#Fix Heights to inches
newDATFIFA <- FIFAdat %>% 
    separate(Height, into = c("H1", "H2"), convert = TRUE) %>%
    transmute(H = H1 * 30.48 + H2 * 2.54)
newDATFIFA$H <- newDATFIFA$H/2.54

#Extract only numeric weight
newDATFIFA$Weight <- strtrim(FIFAdat$Weight,3)




FifaNewDF <- bind_cols(newDATFIFA$H,newDATFIFA$Weight)
colnames(FifaNewDF) <- c("height","weight")
View(FifaNewDF)

colnames(histDF) <- c("Player Position","Height in inches")
View(histDF)


#Look at relationship
p <- ggplot(FifaNewDF, aes(x=weight, y=height)) +geom_point(size=1, shape=1)
p + scale_x_discrete(name ="Player Weight", breaks = seq(90, 300, by = 10))+scale_y_continuous(name="Player Height")+ ggtitle("Player Height vs Weight")+theme_minimal()
 

#Next, assess this relationship between just the LB and LM positions.  (1 slide should do it.)
FifaNewDFPart2 <- bind_cols(newDATFIFA$H,newDATFIFA$Weight,FIFAdat$Position)
colnames(FifaNewDFPart2) <- c("height","weight","position")
PosOfInterest<- filter(FifaNewDFPart2, position == "LB" | position == "LM")

#Look at relationship between LB and LM
g <- ggplot(PosOfInterest, aes(x=weight, y=height,color=position)) +geom_point(size=1, shape=1)
g + scale_x_discrete(name ="Player Weight", breaks = seq(90, 300, by = 10))+scale_y_continuous(name="Player Height")+ ggtitle("Player Height vs Weight")+theme_minimal()



```


```{r}
######################
#                    #
#    Question 3,R    #
#                    #
######################
#Data Munging (30 points): Utilize yob2016.txt for this question. This file is a series of popular children’s names born in the year 2016 in the United States.  It consists of three columns with a first name, a gender, and the amount of children given that name.  However, the data is raw and will need cleaning to make it tidy and usable.
#First, import the .txt file into R so you can process it.  Keep in mind this is not a CSV file.  You might have to open the file to see what you’re dealing with.  Assign the resulting data frame to an object, df, that consists of three columns with human-readable column names for each.
#Display the summary and structure of df
#Your client tells you that there is a problem with the raw file.  One name was entered twice and misspelled.  The client cannot remember which name it is; there are #thousands he saw! But he did mention he accidentally put three y’s at the end of the name.  Write an R command to figure out which name it is and display it.
#Upon finding the misspelled name, please remove this particular observation, as the client says it’s redundant.  Save the remaining dataset as an object: y2016 


#read data
yob2016 <- read.delim("yob2016.txt", sep=";")
colnames(yob2016) <- c("name","gender","count")

#Summary
summary(yob2016)

#Structure
structure(yob2016)

#Find misspelled name
misspelled <- grep("yyy", yob2016$name)
yob2016[misspelled,]
y2016 <- yob2016[-c(211),]
y2016


```

```{r}
######################
#                    #
#    Question 4,R    #
#                    #
######################

#Like 1a, please import the .txt file into R.  Look at the file before you do. #You might have to change some options to import it properly.  Again, please #give the dataframe human-readable column names.  Assign the dataframe to #y2015.  
#Display the last ten rows in the dataframe.  Describe something you find #interesting about these 10 rows.
#Merge y2016 and y2015 by your Name column; assign it to final.  The client #only cares about names that have data for both 2016 and 2015; there should be #no NA values in either of your amount of children rows after merging.

#read data
yob2015 <- read.delim("yob2015.txt", sep=",")
colnames(yob2015) <- c("name","gender","count")

#Summary
summary(yob2015)

#Structure
structure(yob2015)


View(yob2015)

#join
final <- full_join(yob2016, yob2015, by ="name") 

#Remove all NA
final <- final[complete.cases(final), ]

```

```{r}
######################
#                    #
#    Question 5,R    #
#     Labeled 3      #
#                    #
######################


#Data Summary (30 points): Utilize your data frame object final for this part.
#Create a new column called “Total” in final that adds the amount of children in 2015 and 2016 together.  In #those two years combined, how many people were given popular names?
#Sort the data by Total.  What are the top 10 most popular names?
#The client is expecting a girl!  Omit boys and give the top 10 most popular girl’s names.
#Write these top 10 girl names and their Totals to a CSV file.  Leave out the other columns entirely.

total <- (final$count.x)+(final$count.y)
final$total <- total

View(final)


p<-ggplot(final, aes(x=name, y=total, color=gender.x)) +geom_bar(stat="identity")
p
```

